export const ADD_UNINITIALIZED_TARGET = 'ADD_UNINITIALIZED_TARGET';
export const ADD_TARGET = 'ADD_TARGET';
export const CLEAN_INVALID_TARGET = 'CLEAN_INVALID_TARGET';
export const DELETE_TARGET = 'DELETE_TARGET';
export const UPDATE_TARGET = 'UPDATE_TARGET';
