export const SUBMIT_FORM = 'SUBMIT_FORM';
export const SUBMIT_FORM_FULFILLED = 'SUBMIT_FORM_FULFILLED';
export const SUBMIT_FORM_REJECTED = 'SUBMIT_FORM_REJECTED';
export const SCROLL_TO_TOP = 'SCROLL_TO_TOP';
export const DISABLE_SUBMIT_BUTTON = 'DISABLE_SUBMIT_BUTTON';
export const ENABLE_SUBMIT_BUTTON = 'ENABLE_SUBMIT_BUTTON';
