export const ADD_UNINITIALIZED_FRIEND = 'ADD_UNINITIALIZED_FRIEND';
export const ADD_FRIEND = 'ADD_FRIEND';
export const CLEAN_INVALID_FRIENDS = 'CLEAN_INVALID_FRIENDS';
export const DELETE_FRIEND = 'DELETE_FRIEND';
export const UPDATE_FRIEND = 'UPDATE_FRIEND';
